### ISSUE TITLE
pretrained的resnet50_caffe可以上传一下吗

### ISSUE THREAD

**Issue by xskxskxsk** [clelouch/BPFINet#1]
或者可以在哪里下载的到呢

**Comment by clelouch** [comment]
已经上传了
链接：https://pan.baidu.com/s/1K4-b6JPi6E34kgH8gdbYqQ 
提取码：nfih

**Comment by xskxskxsk** [comment]
谢谢！我才看到有传！抱歉！我还想问一下如果训练中途中断了需要重新训练吗，我的result的model里什么也没保存

**Comment by clelouch** [comment]
是的，因为adam的学习率自己也在变，就算中途记录了checkpoint也意义不大。你可以尝试用sgd。这样的话，你就可以每训练一段时间之后自己保存模型参数和学习率，可以用中断点继续训练------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月23日(星期五) 晚上11:47
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [clelouch/BPFINet] pretrained的resnet50_caffe可以上传一下吗 (#1)

**Comment by xskxskxsk** [comment]
好的，非常感谢！
